### ISSUE TITLE
Decompress before Faraday::Response::Json

### ISSUE THREAD

**Issue by jpriollaud** [bodrovis/faraday-gzip#1]
````
connection = Faraday.new do |faraday|
  faraday.request :gzip
  faraday.response :json, parser_options: { symbolize_names: true }, content_type: /\bjson$/, preserve_raw: false
end
````
I'm getting Faraday::ParsingError because the response (coming from VCR) is, apparently, not being decompressed in time to be parsed.  Faraday is trying to parse ASCII.  I'd really like to use the built-in parser rather than use JSON.parse everywhere.

**Comment by bodrovis** [comment]
I'm not sure what's going on here but I have no problems using this gem with VCR and compressed responses. A sample app reproducing this error is very much welcome. Maybe somehow you are using wrong encoding?.. Also, are you sure this issue is related to this solution and not to VCR itself?

**Comment by bodrovis** [comment]
Exploring this issue https://github.com/vcr/vcr/issues/71 and `decode_compressed_response` VCR option might help

**Comment by jpriollaud** [comment]
````
connection = Faraday.new do |faraday|
  faraday.request :gzip
  # faraday.response :json, parser_options: { symbolize_names: true }, content_type: /\bjson$/, preserve_raw: false
end
````
````
JSON.parse(response.body)
# perfectly parsed JSON from a cassette with response body:  encoding: ASCII-8BIT string: !binary |- ...
````

The same test fails if I uncomment the .response :json line

@bodrovis Are you using Faraday's .response :json, parser_options ?

**Comment by bodrovis** [comment]
Nope, I'm not using that add-on to be honest. I suspect it has something to do with VCR's own decompression, perhaps. In other words, I'm not sure it has anything to do with gzip but it's quite hard to say. I'll try to look into it.

**Comment by bodrovis** [comment]
I have to mention that many modern adapters should perform decompression without using gzip gem at all so chances are you don't need this gem and the line `faraday.request :gzip` might be redundant

**Comment by bodrovis** [comment]
More info here https://github.com/lostisland/awesome-faraday/#adapters

**Comment by jpriollaud** [comment]
You are right, faraday.request :gzip is not the right approach.  I'm using Typhoeus and decode_compressed_response did not help.  I'll just rebuild the tests or use a patch.  Let's close this.  Thank you for your guidance, I appreciate it.

**Comment by jpriollaud** [comment]
Solved with:

`faraday.use CustomGzipMiddleware if Rails.env.test?`

````
class CustomGzipMiddleware < Faraday::Gzip::Middleware
  def call(env)
      # _DISABLED_ env[:request_headers][ACCEPT_ENCODING] ||= SUPPORTED_ENCODINGS
      @app.call(env).on_complete do |response_env|
      if response_env[:body].empty?
        reset_body(response_env) { |body| raw_body(body) }
      else
        case response_env[:response_headers][CONTENT_ENCODING]
        when 'gzip'
          reset_body(response_env) { |body| uncompress_gzip(body) }
        when 'deflate'
          reset_body(response_env) { |body| inflate(body) }
        when 'br'
          reset_body(response_env) { |body| brotli_inflate(body) }
        end
      end
    end
  end
end
````

Your module saved me days of work.  It's a real shame VCR doesn't provide better backward compatibility for cassettes.

**Comment by bodrovis** [comment]
I'm glad it is solved now, thank you :)
